name: App CI
on: [push]
env:
  KESKO_PROJECT_ID: url-to-pdf-api
  IMAGE_NAME: api
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build-dev:
    name: "Build and push Docker image to development registry"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault.cloud.keskodev.zone
          method: approle
          roleId: ${{ secrets.DEV_VAULT_ROLE_ID }}
          secretId: ${{ secrets.DEV_VAULT_SECRET_ID }}
          secrets: |
            gcp/roleset/${{ env.KESKO_PROJECT_ID }}/key private_key_data | GCP_SA_KEY ;
            secret/data/${{ env.KESKO_PROJECT_ID }}/init docker_repository_url | DOCKER_REPOSITORY_URL ;
            secret/data/shared/npm npm_token | NPM_TOKEN ;
            secret/data/shared/gcp region | GCP_REGION ;

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ steps.secrets.outputs.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Login to Artifact Registry
        run: gcloud auth configure-docker ${{ steps.secrets.outputs.GCP_REGION }}-docker.pkg.dev

      - name: Install Buildpack
        uses: buildpacks/github-actions/setup-pack@v4.1.0

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: NPM_TOKEN=${{ steps.secrets.outputs.NPM_TOKEN }}
          tags: ${{ steps.secrets.outputs.DOCKER_REPOSITORY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          push: true

  deploy-dev:
    name: "Deploy API to development"
    runs-on: ubuntu-latest
    needs: build-dev
    environment: development
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault.cloud.keskodev.zone
          method: approle
          roleId: ${{ secrets.DEV_VAULT_ROLE_ID }}
          secretId: ${{ secrets.DEV_VAULT_SECRET_ID }}
          secrets: |
            gcp/roleset/${{ env.KESKO_PROJECT_ID }}/key private_key_data | GCP_SA_KEY ;
            secret/data/${{ env.KESKO_PROJECT_ID }}/init k8s_namespace | K8S_NAMESPACE ;
            secret/data/shared/gcp project_id | GCP_PROJECT_ID ;
            secret/data/shared/gcp region | GCP_REGION ;

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ steps.secrets.outputs.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE credentials
        run: >-
          gcloud container clusters get-credentials main
          --region ${{ steps.secrets.outputs.GCP_REGION }}
          --project ${{ steps.secrets.outputs.GCP_PROJECT_ID }}

      - name: Login to Helm repository
        run: >-
          gcloud auth application-default print-access-token |
          helm registry login -u oauth2accesstoken
          --password-stdin https://${{ steps.secrets.outputs.GCP_REGION }}-docker.pkg.dev
        env:
          HELM_EXPERIMENTAL_OCI: "1"

      - name: Deploy application to development
        run: >-
          helm upgrade
          --install
          --values $GITHUB_WORKSPACE/envs/dev.yaml
          --set "image.tag=${{ env.IMAGE_TAG }}"
          --namespace ${{ steps.secrets.outputs.K8S_NAMESPACE }}
          dev
          $GITHUB_WORKSPACE/charts/url-to-pdf-api
